import "./globals.css";
import DarkModeProvider from "../components/theme-provider";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <DarkModeProvider>
          <Navbar />
          <Sidebar />
          <div className="lg:pl-72 ">
            <main>
              <div className="w-full ">{children}</div>
            </main>
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
