import "./globals.css";
import "nprogress/nprogress.css";
import DarkModeProvider from "../components/theme-provider";
import { NavigationEvents } from "@/components/navigation-event";
import { Confirmer } from "@/components/confirmer";
import Notifier from "@/components/notifier";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NavigationEvents />
        <DarkModeProvider>
          <main>
            <div>{children}</div>
          </main>
          <Confirmer />
          <Notifier />
        </DarkModeProvider>
      </body>
    </html>
  );
}
